import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'beautiful animations',
      url: 'https://beautiful-animations-kv.vercel.app/',
      repo: 'https://github.com/vatsalsinghkv/beautiful-animations',
      img: '/tumblr.gif',
      year: 2023,
      tags: ['CSS Animations', 'Sass'],
    },
    {
      id: getId(),
      name: 'easy fix',
      url: 'https://easy-fix.vercel.app/',
      repo: 'https://github.com/vatsalsinghkv/easy-fix',
      img: '/tumblr.gif',
      year: 2023,
      tags: ['React', 'Tailwind'],
    },
    {
      id: getId(),
      name: 'image animations',
      url: 'https://image-animations.vercel.app/',
      repo: 'https://github.com/vatsalsinghkv/image-animations',
      img: '/tumblr.gif',
      year: 2023,
      tags: ['CSS Animations', 'Sass'],
    },
    {
      id: getId(),
      name: 'remotive jobs',
      url: 'https://remotive-jobs.vercel.app/',
      repo: 'https://github.com/vatsalsinghkv/remotive-jobs',
      img: '/tumblr.gif',
      year: 2022,
      tags: ['Nextjs', 'Sass'],
    },
    {
      id: getId(),
      name: 'countries app',
      url: 'https://countries-app-kv.netlify.app/',
      repo: 'https://github.com/vatsalsinghkv/rest-countries-api',
      img: '/tumblr.gif',
      year: 2022,
      tags: ['React', 'Sass'],
    },
    {
      id: getId(),
      name: 'rock paper scissors',
      url: 'https://rock-paper-scissors-kv.netlify.app/',
      repo: 'https://github.com/vatsalsinghkv/rock-paper-scissors',
      img: '/tumblr.gif',
      year: 2022,
      tags: ['React', 'Sass'],
    },
    {
      id: getId(),
      name: 'todo app',
      url: 'https://todo-kv.netlify.app/',
      repo: 'https://github.com/vatsalsinghkv/todo-app',
      img: '/tumblr.gif',
      year: 2022,
      tags: ['React', 'Sass', 'JS'],
    },
    {
      id: getId(),
      name: 'weather app',
      url: 'https://weather-kv.netlify.app/',
      repo: 'https://github.com/vatsalsinghkv/weather-app',
      img: '/tumblr.gif',
      year: 2022,
      tags: ['Html', 'sass', 'JS', 'jQuery'],
    },
    {
      id: getId(),
      name: 'blogr landing page',
      url: 'https://blogr-kv.netlify.app/',
      repo: 'https://github.com/vatsalsinghkv/blogr-landing-page',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'sass', 'JS'],
    },
    {
      id: getId(),
      name: 'natours',
      url: 'https://natours-kv.netlify.app/',
      repo: 'https://github.com/vatsalsinghkv/natours',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'sass', 'JS'],
    },
    {
      id: getId(),
      name: 'nexter',
      url: 'https://vatsalsinghkv.github.io/nexter/',
      repo: 'https://github.com/vatsalsinghkv/nexter',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'sass'],
    },
    {
      id: getId(),
      name: 'IP address tracker',
      url: 'https://vatsalsinghkv.github.io/ip-address-tracker/',
      repo: 'https://github.com/vatsalsinghkv/ip-address-tracker',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'bootstrap', 'JS'],
    },
    {
      id: getId(),
      name: 'calculator app',
      url: 'https://vatsalsinghkv.github.io/calculator-app/',
      repo: 'https://github.com/vatsalsinghkv/calculator-app/',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'pig game',
      url: 'https://vatsalsinghkv.github.io/pig-game/',
      repo: 'https://github.com/vatsalsinghkv/pig-game',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'bankist marketing',
      url: 'https://vatsalsinghkv.github.io/bankist-marketing/',
      repo: 'https://github.com/vatsalsinghkv/bankist-marketing',
      img: '/tumblr.gif',
      year: 2021,
      tags: ['html', 'CSS', 'JS'],
    },
  ],
};
