export const seo = {
    title: 'Rafael Jongco | Software Developer, AI & Web Design Expert',
    description:
      'Rafael Jongco is a software developer and expert in building and designing applications, websites, AI solutions, chatbots, and more. Passionate about creating innovative and user-centric digital experiences.',
    author: 'Rafael Jongco',
    image: '/profile.jpg',
    url: 'https://rafaeljongco.com',
    keywords: [
      'Rafael Jongco',
      'Software Developer',
      'AI Expert',
      'Web Developer',
      'Web Design',
      'UI/UX Design',
      'AI Solutions',
      'Chatbot Development',
      'Machine Learning',
      'Frontend Development',
      'Backend Development',
      'Programming Expert',
      'Software Engineering',
      'Full Stack Development',
      'Tech Portfolio',
      'Digital Innovation',
      'Application Development',
      'Tech Consultant',
      'Web Design Expert',
      'UX/UI Designer',
      'Chatbot Expert',
      'AI Developer',
      'Rafael Jongco Portfolio',
      'Rafael Jongco Software Development',
    ],
  };
  